name: ArcticDeathChest
version: '1.1.0'
main: dev.arctic.arcticdeathchest.ArcticDeathChest
# Note: api-version is intentionally omitted for 1.7.10-1.12 compatibility
# The plugin handles version differences internally
author: Antry
description: A plugin that creates death chests when players die with falling animations and holograms
website: https://github.com/GrayCloudsBR/ArcticDeathChest

# Soft dependencies - plugin will work without these but can integrate if present
softdepend: []

# Load order
load: POSTWORLD

# Commands
commands:
  arcticdeathchest:
    description: Main command for ArcticDeathChest plugin
    usage: /arcticdeathchest [reload|info]
    aliases: [adl, deathchest, dc]

# Permissions
permissions:
  arcticdeathchest.*:
    description: Gives access to all ArcticDeathChest features
    default: op
    children:
      arcticdeathchest.create: true
      arcticdeathchest.break: true
      arcticdeathchest.admin: true

  arcticdeathchest.create:
    description: Allows a player to have a death chest created when they die
    default: true

  arcticdeathchest.break:
    description: Allows a player to manually break death chests
    default: true

  arcticdeathchest.admin:
    description: Allows access to admin commands (reload, etc)
    default: op
